print("Selamat datang di Band Name Generator,\ntempat kamu mendapatkan nama band impianmu!")
print("\nSilakan jawab pertanyaan berikut guna membantu kami membuat nama band-mu ;)\n")
print("Pertanyaan #1")
print("Di mana kamu tinggal sekarang?\n")
domisili = input("(ketik + enter jawaban di sini): ")
print("\nPertanyaan #2")
print("Siapa nama hewan peliharaanmu?\n")
nama_peliharaan = input("(ketik + enter jawaban di sini): ")
print("Oke, ini dia nama band barumu!: " + domisili + " " + nama_peliharaan)
